'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '..');
const read = relativePath => fs.readFileSync(path.join(root, relativePath), 'utf8');

test('side panel hosts SID, DOI search, and UUID export without page overlays', () => {
  const html = read('public/sidepanel.html');
  const popup = read('src/popup.js');
  const contentScript = read('src/contentScript.js');
  const sidepanelTools = read('src/sidepanel-wos-tools.js');
  const sidepanelCss = read('src/sidepanel.css');

  assert.match(html, /id="wosSidValue"/);
  assert.doesNotMatch(html, /wos\.quickTitle|WOS Quick Actions/);
  assert.match(html, /id="copyWosSidBtn"/);
  assert.match(html, /id="wosDoiToolPanel"/);
  assert.match(html, /id="wosDoiQueryInput"[^>]*data-i18n-title="wos\.doiDropTitle"/);
  assert.match(html, /id="wosUuidToolPanel"/);
  assert.match(html, /id="runWosDoiSearchBtn"/);
  assert.match(html, /id="runWosUuidExportBtn"/);
  assert.match(html, /id="scholarJournalInput"/);
  assert.match(html, /id="searchScholarRankBtn"/);
  assert.match(popup, /func:\s*resolveWosSidInMainWorld/);
  assert.match(sidepanelTools, /export_range_data/);
  assert.match(sidepanelTools, /FETCH_EASYSCHOLAR_RANK/);
  assert.match(sidepanelTools, /id: 'doi-download', tab: elements\.doiDownloadTab, panel: elements\.doiDownloadPanel/);
  assert.match(sidepanelTools, /setToolPanel\('doi-download'\)/);
  assert.match(sidepanelTools, /IDENTIFIER_FILE_EXTENSIONS = new Set\(\['txt', 'bib', 'md', 'json', 'xml', 'ris', 'csv'\]\)/);
  assert.match(sidepanelTools, /importIdentifierFiles/);
  assert.match(sidepanelTools, /addEventListener\('drop'/);
  assert.match(sidepanelTools, /SCHOLAR_HISTORY_KEY = 'wosAideScholarQueryHistory'/);
  assert.match(sidepanelTools, /MAX_SCHOLAR_HISTORY_ITEMS = 30/);
  assert.match(sidepanelTools, /saveScholarHistory\(journal, response\.result\)/);
  assert.match(sidepanelTools, /scholarHistory\.filter\(item => item\.favorite\)/);
  assert.match(sidepanelTools, /orderScholarHistory/);
  assert.match(sidepanelTools, /history-favorite-button/);
  assert.match(sidepanelTools, /scholarParentTab\?\.addEventListener\('click', \(\) => setScholarSubPanel\('scholarQuerySubPanel'\)\)/);
  assert.match(sidepanelTools, /wos-aide:wos-tab-activated/);
  assert.match(sidepanelCss, /\.wos-inner-panel\[hidden\]\s*\{\s*display:\s*none/);
  assert.match(sidepanelCss, /\.doi-file-drop-target\.is-file-dragover[^}]*border-style:\s*dashed[^}]*rgba\(82, 82, 91, \.09\)/);
  assert.match(sidepanelCss, /\.button:disabled:hover[\s\S]{0,180}pointer-events:\s*none/);
  assert.match(sidepanelCss, /\.button:disabled i\s*\{\s*color:\s*inherit/);
  assert.doesNotMatch(html, /diagnoseWosBtn|Diagnose WOS Page/);
  assert.doesNotMatch(popup, /WOS connection failed:/);
  assert.match(contentScript, /action:\s*request\.preferredTab === 'journal' \? 'sidepanel-scholar' : 'sidepanel-wos'/);
  assert.doesNotMatch(contentScript, /bootstrapWosToolbarShortcuts\(\);\s*ensureWosToolbarShortcuts\(\);/);
});

test('side panel exposes tool and settings views', () => {
  const html = read('public/sidepanel.html');
  const sidepanelSource = read('src/sidepanel.js');
  const journalListStorage = read('src/my-journal-list-storage.js');
  const sidepanelCss = read('src/sidepanel.css');
  const wechatSupportQrPath = path.join(root, 'public/images/wechat-support-qr.png');
  const alipaySupportQrPath = path.join(root, 'public/images/alipay-support-qr.png');
  assert.match(html, /id="tabCnki"/);
  assert.match(html, /id="tabWos"/);
  assert.doesNotMatch(html, /id="tabDoi"|id="doiPanel"/);
  assert.match(html, /id="tabLlm"/);
  assert.match(html, /id="tabScholar"/);
  assert.match(html, /id="tabMyJournals"[^>]*data-panel="myJournalsPanel"/);
  assert.match(html, /id="tabCrossref"/);
  assert.match(html, /id="tabSettings"/);
  assert.match(html, /data-i18n="nav\.access">Full Text</);
  assert.match(html, /id="tabLlm"[\s\S]*id="tabWos"[\s\S]*id="tabCrossref"[\s\S]*id="tabLibraryAccess"[\s\S]*id="tabScholar"[\s\S]*id="tabMyJournals"[\s\S]*id="tabSettings"[\s\S]*id="tabCnki"/);
  assert.match(html, /id="tabCnki"[^>]*hidden/);
  assert.match(html, /id="downloadBtn"/);
  assert.doesNotMatch(html, /id="nativeDownloadBtn"/);
  assert.match(html, /id="openaiSettingsPanel"/);
  assert.match(html, /id="llmChatMessages"/);
  assert.match(html, /id="sendLlmChatBtn"/);
  assert.match(html, /id="easyScholarSettingsPanel"/);
  assert.match(html, /id="scholarConfigSubTab"/);
  assert.match(html, /id="scholarQuerySubTab"/);
  assert.match(html, /id="scholarHistorySubTab"/);
  assert.match(html, /id="scholarQuerySubTab"[\s\S]*id="scholarHistorySubTab"[\s\S]*id="scholarConfigSubTab"/);
  assert.match(html, /id="scholarHistoryList"/);
  assert.match(html, /id="easyScholarWebsiteBtn"[\s\S]*data-i18n="scholar\.apiKey"/);
  assert.match(html, /id="settingsLanguageSubTab"/);
  assert.match(html, /id="settingsSupportSubTab"/);
  assert.match(html, /id="settingsAboutSubTab"/);
  assert.match(html, /id="crossrefSearchSubTab"/);
  assert.match(html, /id="crossrefPreviewSubTab"/);
  assert.match(html, /id="crossrefHistorySubTab"/);
  assert.match(html, /id="crossrefSelectAllResults"[\s\S]*id="crossrefBibPreview"[\s\S]*id="crossrefSelectAllHistory"/);
  assert.match(html, /id="wosDoiDownloadToolTab"[\s\S]*aria-controls="wosDoiDownloadToolPanel"/);
  assert.match(html, /id="wosDoiDownloadToolPanel"[\s\S]*id="doiBatchHost"/);
  assert.match(html, /id="settingsShowCnkiTab"[^>]*type="checkbox"/);
  assert.doesNotMatch(html, /id="settingsShowCnkiTab"[^>]*checked/);
  assert.match(html, /id="settingsShowWosTab"[^>]*type="checkbox"[^>]*checked/);
  assert.match(html, /id="settingsShowLlmTab"[^>]*type="checkbox"[^>]*checked/);
  assert.match(html, /id="settingsShowScholarTab"[^>]*type="checkbox"[^>]*checked/);
  assert.match(html, /id="settingsShowMyJournalsTab"[^>]*type="checkbox"[^>]*checked/);
  assert.match(html, /id="settingsShowCrossrefTab"[^>]*type="checkbox"[^>]*checked/);
  assert.match(html, /id="settingsSupportSubPanel"[\s\S]*images\/wechat-support-qr\.png/);
  assert.match(html, /id="settingsSupportSubPanel"[\s\S]*images\/alipay-support-qr\.png/);
  assert.match(html, /id="supportPaymentWechat" class="[^"]*is-active"[\s\S]*aria-pressed="true"/);
  assert.match(html, /id="supportPaymentAlipay"[\s\S]*aria-pressed="false"/);
  assert.match(html, /id="supportPaymentMacApp"[\s\S]*data-support-payment="mac-app"[\s\S]*aria-pressed="false"/);
  assert.match(html, /id="supportAlipayQr"[\s\S]*hidden/);
  assert.match(html, /id="supportMacAppPanel"[\s\S]*data-support-payment-panel="mac-app"[\s\S]*hidden/);
  assert.match(html, /apps\.apple\.com\/app\/wos-aide-bar\/id6795536028/);
  assert.match(html, /wosaide\.github\.io\/wosaide-bar-site\//);
  assert.match(html, /Apple App Store 中搜索“WOSAide”/);
  assert.match(html, /¥0\.66[\s\S]*¥0\.99[\s\S]*¥1/);
  assert.match(html, /settings-support-notice[\s\S]*data-i18n="settings\.supportDescription"/);
  assert.doesNotMatch(html, /settings\.supportVoluntary/);
  assert.match(html, /settings-support-payment-label[\s\S]*data-i18n="settings\.supportWechat"/);
  assert.doesNotMatch(html, /settings\.supportTitle/);
  assert.match(html, /id="settingsExtensionVersion"/);
  assert.match(html, /github\.com\/iihciyekub\/wos-aide-extension/);
  assert.match(sidepanelSource, /activatePanel/);
  assert.match(sidepanelSource, /settingsPanel:\s*'Settings'/);
  assert.match(sidepanelSource, /version\.textContent = extensionVersion/);
  assert.match(sidepanelSource, /settingsSupportSubPanel/);
  assert.match(sidepanelSource, /initializeJournalCatalog\(\)/);
  assert.doesNotMatch(sidepanelSource, /settingsJournalSubPanel/);
  assert.match(sidepanelSource, /tabVisibilityOptions/);
  assert.match(sidepanelSource, /wosAideShowMyJournalsTab/);
  assert.match(sidepanelSource, /option\.tab\.hidden = !show/);
  assert.match(sidepanelSource, /\.tab-bar \.tab-button:not\(\[hidden\]\)/);
  assert.match(sidepanelSource, /crossrefPanel:\s*'Crossref Literature Search'/);
  assert.match(sidepanelSource, /initializeCrossrefPanel\(\)/);
  assert.match(sidepanelSource, /setSupportPayment\('wechat'\)/);
  assert.match(sidepanelSource, /setSettingsSubPanel\('settingsSupportSubPanel'\);\s*setSupportPayment\('wechat'\)/);
  assert.doesNotMatch(sidepanelSource, /wosAideSettingsSubTab/);
  assert.match(sidepanelSource, /activatePanel\(button && !button\.hidden \? requested : 'llmPanel'\)/);
  assert.match(journalListStorage, /DEFAULTS_INITIALIZED_KEY = 'defaults-initialized'/);
  assert.match(journalListStorage, /if \(defaultsInitialized !== true\)/);
  assert.match(journalListStorage, /lists\[0\]\?\.id \|\| ''/);
  assert.match(sidepanelSource, /typeof result\[option\.storageKey\] === 'boolean' \? result\[option\.storageKey\] : option\.defaultVisible/);
  assert.match(sidepanelSource, /!show && option\.tab\?\.classList\.contains\('is-active'\)/);
  assert.ok(fs.statSync(wechatSupportQrPath).size > 0);
  assert.ok(fs.statSync(alipaySupportQrPath).size > 0);
  assert.match(sidepanelCss, /\.llm-composer\s*\{[^}]*margin:\s*auto 0 0/);
  assert.match(sidepanelCss, /\.scholar-sub-tabs\s*\{[^}]*grid-template-columns:\s*repeat\(3/);
  assert.match(sidepanelCss, /\.tool-switch-button\s*\{[^}]*font-size:\s*10\.5px[^}]*font-weight:\s*600/);
  assert.doesNotMatch(sidepanelCss, /\.(?:scholar|crossref)-sub-tabs \.tool-switch-button\s*\{[^}]*font-size:/);
  assert.match(sidepanelCss, /\.settings-support-payment-switch\s*\{[^}]*grid-template-columns:\s*repeat\(3/);
  assert.match(sidepanelCss, /\.settings-sub-tabs\s*\{[^}]*grid-template-columns:\s*repeat\(3/);
  assert.match(sidepanelCss, /\.settings-support-payment-option span\s*\{[^}]*white-space:\s*nowrap/);
  assert.match(sidepanelCss, /\.tab-bar\s*\{[^}]*repeat\(var\(--visible-tab-count, 7\)/);
  assert.match(sidepanelCss, /#crossrefPanel\s*\{[^}]*flex:\s*1[^}]*height:\s*100%[^}]*overflow:\s*hidden/);
  assert.match(sidepanelCss, /\.crossref-sub-tabs\s*\{[^}]*grid-template-columns:\s*repeat\(4/);
  assert.match(sidepanelCss, /\.wos-sub-tabs\s*\{[^}]*grid-template-columns:\s*repeat\(3/);
  assert.match(sidepanelCss, /\.settings-toggle input:checked \+ span\s*\{[^}]*background:\s*#202123/);
  assert.match(sidepanelCss, /\.button--primary\s*\{[^}]*background:\s*#fff[^}]*color:\s*var\(--text\)/);
  assert.doesNotMatch(sidepanelCss, /\.button--primary\s*\{[^}]*(?:background|border-color):\s*#202123/);
  assert.match(sidepanelCss, /\.my-journal-list-tab\.is-active\s*\{[^}]*background:\s*#ececec[^}]*color:\s*#111/);
  assert.match(sidepanelCss, /#doiBatchHost \.doi-download-primary\s*\{[^}]*background:\s*#fff !important[^}]*color:\s*var\(--text\) !important/);
  assert.match(html, /id="journalCatalogFileInput"/);
  assert.match(html, /id="journalCatalogRemoteBtn"/);
  assert.match(html, /id="journalCatalogVersion"/);
  assert.match(html, /id="journalCatalogGithubLink"[^>]+class="icon-button journal-catalog-github"/);
  assert.match(html, /id="scholarConfigSubPanel"[\s\S]*id="journalCatalogFileInput"/);
  assert.doesNotMatch(html, /id="settingsJournalSubPanel"/);
  assert.match(html, /github\.com\/wosaide\/wosaide-journal-lists/);
  assert.match(html, /id="journalSuggestionMenu"/);
  assert.match(html, /id="myJournalsPanel"[^>]*aria-labelledby="tabMyJournals"/);
  assert.match(sidepanelCss, /#wosPanel\s*\{[^}]*flex:\s*1[^}]*height:\s*100%[^}]*overflow:\s*hidden/);
  assert.match(sidepanelCss, /#wosDoiToolPanel\s*\{[^}]*flex:\s*1[^}]*min-height:\s*0[^}]*padding:\s*0[^}]*border:\s*0[^}]*background:\s*transparent/);
  assert.match(sidepanelCss, /#wosDoiQueryInput\s*\{[^}]*flex:\s*1 0 105px[^}]*min-height:\s*105px[^}]*font-family:\s*inherit/);
  assert.match(sidepanelCss, /#wosDoiToolPanel \.button\s*\{[^}]*min-height:\s*31px[^}]*border-radius:\s*6px/);
  assert.match(sidepanelCss, /\.wos-doi-download-panel\s*\{[^}]*flex:\s*1[^}]*height:\s*100%[^}]*overflow:\s*hidden/);
  assert.match(sidepanelCss, /\.doi-batch-host\s*\{[^}]*height:\s*100%[^}]*flex:\s*1/);
  assert.match(sidepanelCss, /#doiBatchHost \.doi-batch-content\s*\{[^}]*flex:\s*1 !important[^}]*overflow-y:\s*auto !important/);
  assert.match(sidepanelCss, /#doiBatchHost \.doi-batch-log\s*\{[^}]*border-top:\s*0 !important/);
  const doiDownloadSource = read('src/z-doi-pdf-download.js');
  assert.match(doiDownloadSource, /logDiv\.className = "doi-batch-log"/);
  assert.match(doiDownloadSource, /textarea\.addEventListener\("dragenter"/);
  assert.match(doiDownloadSource, /textarea\.addEventListener\("drop"/);
  assert.match(doiDownloadSource, /textarea\.classList\.add\("doi-file-drop-target"\)/);
  assert.doesNotMatch(doiDownloadSource, /dropOverlay/);
});

test('my journal editor uses full-height side-panel tabs instead of a dialog', () => {
  const html = read('public/sidepanel.html');
  const source = read('src/sidepanel-my-journals.js');
  const css = read('src/sidepanel.css');
  assert.match(html, /id="myJournalsListSubTab"[^>]*aria-controls="myJournalsListSubPanel"/);
  assert.match(html, /id="myJournalsEditorSubTab"[^>]*aria-controls="myJournalsEditorSubPanel"/);
  assert.doesNotMatch(html, /<dialog[^>]+id="myJournalsEditorDialog"/);
  assert.doesNotMatch(source, /showModal\(|\.dialog\.close\(/);
  assert.match(css, /\.my-journals-sub-tabs\s*\{[^}]*grid-template-columns:\s*repeat\(2/);
  assert.match(css, /\.my-journals-editor-card\s*\{[^}]*min-height:\s*0[^}]*flex:\s*1/);
  assert.match(css, /\.my-journals-editor-textarea\s*\{[^}]*flex:\s*1[^}]*resize:\s*none/);
});
