'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '..');
const read = relativePath => fs.readFileSync(path.join(root, relativePath), 'utf8');
const manifest = JSON.parse(read('public/manifest.json'));
const packageInfo = JSON.parse(read('package.json'));
const sidepanel = read('src/sidepanel.js');
const sidepanelHtml = read('public/sidepanel.html');
const sidepanelCss = read('src/sidepanel.css');
const background = read('src/background.js');
const libraryAccess = read('src/sidepanel-library-access.js');

test('extension action opens the native Chrome side panel', () => {
  assert.equal(manifest.name, 'Overleaf texAide');
  assert.match(manifest.version, /^\d+\.\d+\.\d+$/);
  assert.equal(manifest.version, packageInfo.version);
  assert.equal(manifest.side_panel.default_path, 'sidepanel.html');
  assert.equal(manifest.action.default_popup, undefined);
  assert.ok(manifest.permissions.includes('sidePanel'));
  assert.ok(manifest.permissions.includes('downloads'));
  assert.ok(!manifest.permissions.includes('debugger'));
  assert.deepEqual(manifest.host_permissions, ['http://*/*', 'https://*/*']);
  const generalScripts = manifest.content_scripts.filter(item => item.js.includes('contentScript.js'));
  assert.equal(generalScripts.length, 1);
  assert.deepEqual(generalScripts[0].matches, ['http://*/*', 'https://*/*']);
  const wosLoader = manifest.content_scripts.find(item => item.js.includes('z-Wos-loader.js'));
  assert.ok(wosLoader.matches.includes('https://www.webofscience.com/*'));
  assert.ok(!wosLoader.matches.includes('https://*/*'));
  assert.match(background, /openPanelOnActionClick:\s*true/);
  assert.match(sidepanelHtml, /id="downloadBtn"/);
  assert.doesNotMatch(sidepanelHtml, /id="nativeDownloadBtn"/);
  assert.match(sidepanelHtml, /id="chooseFolderLabel"/);
  assert.match(sidepanelHtml, /id="folderPermission"/);
  assert.match(sidepanelHtml, /id="downloadIntervalSeconds"/);
  assert.match(sidepanelHtml, /id="skipExistingPdfs"/);
  assert.match(sidepanelHtml, />CNKI Overseas Login<\/a>/);
  assert.match(sidepanelHtml, /fsso\.oversea\.cnki\.net\/login_en\.aspx\?lang=zh-TW&amp;returnUrl=https%3A%2F%2Ftra\.oversea\.cnki\.net%2Fkns%3Fdbcode%3DCFLQ/);
  assert.match(sidepanelHtml, /title="CNKI Overseas Login"/);
  assert.match(sidepanelHtml, /id="doiBatchHost"/);
  assert.match(sidepanelHtml, /role="tablist"/);
  assert.match(sidepanelCss, /\.sidepanel-app \{[^}]*padding: 0;/);
  assert.doesNotMatch(sidepanelHtml, /openSettingsBtn|popup\.html/);
  assert.match(sidepanel, /chrome\.runtime\.getManifest\(\)\?\.version/);
  assert.match(sidepanel, /document\.title = `WOS Aide v\$\{extensionVersion\}`/);
  assert.doesNotMatch(sidepanel, /Reload extension version \d+\.\d+\.\d+/);
});

test('side panel performs CNKI page-click downloads with selected-folder deduplication', () => {
  assert.match(sidepanel, /showDirectoryPicker/);
  assert.match(sidepanel, /crypto\.subtle\.digest\('SHA-256'/);
  assert.match(sidepanel, /knownHashes/);
  assert.match(sidepanel, /buildCnkiUrlHashIndex/);
  assert.match(sidepanel, /GET_CNKI_PDF_LINKS/);
  assert.match(sidepanel, /world:\s*'MAIN'/);
  assert.match(sidepanel, /triggerCnkiTrustedDownload/);
  assert.match(sidepanel, /captureCnkiPdfWithTrustedClick/);
  assert.match(sidepanel, /Input\.dispatchMouseEvent/);
  assert.match(sidepanel, /waitForChromeDownloadCompletion/);
  assert.match(sidepanel, /Clicking CNKI PDF icons in the logged-in page/);
  assert.match(sidepanel, /abbreviateMiddle/);
  assert.match(sidepanel, /Folder: \$\{abbreviateMiddle\(name, 22\)\}/);
  assert.match(sidepanel, /downloadLog\.textContent = line/);
  assert.doesNotMatch(sidepanel, /downloadLog\.textContent = `\[\$\{timestamp\}\] \$\{message\}\\n/);
  assert.match(sidepanel, /prepareDirectoryDeduplication/);
  assert.match(sidepanel, /linkExistsInDirectory/);
  assert.match(sidepanel, /indexCompletedPageDownload/);
  assert.match(sidepanel, /downloadIntervalMs/);
  assert.match(sidepanel, /refreshDirectoryDeduplication/);
  assert.match(sidepanel, /renderDownloadAvailability/);
  assert.match(sidepanel, /for \(const link of linksToDownload\)/);
  assert.match(sidepanel, /PDF link.*already in the selected folder.*ready to download/);
  assert.match(sidepanelHtml, /PDFs ready to download/);
  assert.doesNotMatch(sidepanel, /verificationVisible|verificationWarning/);
  assert.doesNotMatch(sidepanelHtml, /security verification/i);
  assert.match(sidepanelHtml, /Download PDFs/);
  assert.match(sidepanelHtml, /authenticated page-click responses are captured and written there/);
  assert.match(sidepanel, /require\('\.\/z-doi-pdf-download'\)/);
});

test('side panel exposes institutional DOI access as a parent tab', () => {
  assert.match(sidepanelHtml, /id="tabLibraryAccess"[^>]+data-panel="libraryAccessPanel"/);
  assert.match(sidepanelHtml, /id="libraryAccessSearch"/);
  assert.match(sidepanelHtml, /id="libraryAccessDoiInput"/);
  assert.match(sidepanelHtml, /id="clearLibraryAccessDoisBtn"/);
  assert.match(sidepanelHtml, /data-i18n="access\.clearInput"/);
  assert.match(sidepanelHtml, /data-i18n-title="access\.clearInput"/);
  assert.match(sidepanelHtml, /id="resolveLibraryAccessBtn"/);
  assert.match(sidepanelHtml, /id="libraryAccessQuerySubTab"/);
  assert.match(sidepanelHtml, /id="libraryAccessConfigSubTab"/);
  assert.match(sidepanelHtml, /id="libraryAccessHistorySubTab"/);
  assert.match(sidepanelHtml, /id="libraryAccessSearchMode"/);
  assert.match(sidepanelHtml, /id="libraryAccessHistoryList"/);
  assert.match(sidepanelHtml, /libraryAccessDoiInput[^>]+doi-file-drop-target/);
  assert.match(libraryAccess, /clearDois\.disabled = running \|\| elements\.doiInput\.value\.length === 0/);
  assert.match(libraryAccess, /elements\.doiInput\.value = ''/);
  assert.match(libraryAccess, /t\('access\.inputCleared'\)/);
  assert.match(sidepanel, /initializeLibraryAccess\(\)/);
  assert.match(sidepanelHtml, /class="library-access-institution-row"[\s\S]*id="libraryAccessInstitutionSelect"/);
  assert.doesNotMatch(sidepanelHtml, /<label[^>]+for="libraryAccessDoiInput"[^>]*>DOI<\/label>/);
  assert.doesNotMatch(sidepanelHtml, /flat-card library-access-query-card/);
  assert.match(sidepanelHtml, /class="library-access-institution-control"[\s\S]*id="libraryAccessInstitutionSelect"[\s\S]*id="resolveLibraryAccessBtn"/);
  assert.match(sidepanelHtml, /class="flat-card library-access-results-card"[\s\S]*id="libraryAccessStatus"[\s\S]*id="libraryAccessResults"/);
  assert.match(sidepanelHtml, /id="libraryAccessConfiguredToggle"[^>]*aria-expanded="true"[^>]*aria-controls="libraryAccessConfiguredBody"/);
  assert.match(sidepanelHtml, /data-i18n="access\.searchTitle"[\s\S]*data-i18n="access\.searchDescription"/);
  assert.match(libraryAccess, /configuredCollapsed/);
  assert.match(libraryAccess, /action\.addEventListener\('click', \(\) => \{\s*if \(item\.accessUrl\) chrome\.tabs\.create\(\{ url: item\.accessUrl, active: true \}\);/);
  assert.match(libraryAccess, /const linkedHistory = history\.filter\(item => item\.accessUrl\)/);
  assert.match(sidepanelHtml, /class="flat-card library-access-history-card"/);
  assert.match(sidepanelCss, /\.library-access-history-list\s*\{[^}]*flex:\s*1[^}]*overflow-y:\s*auto/);
  assert.match(libraryAccess, /history = history\.filter\(item => item\.favorite\)/);
  assert.match(libraryAccess, /history-favorite-button/);
  assert.match(libraryAccess, /importDoiFiles/);
  assert.match(libraryAccess, /event\.dataTransfer\?\.files/);
  assert.match(libraryAccess, /scheduleAutoResolve/);
  assert.match(libraryAccess, /const resolveIncremental/);
  assert.match(libraryAccess, /const normalizeDoiInput/);
  assert.match(libraryAccess, /elements\.doiInput\.value = dois\.join\('\\n'\)/);
  assert.match(libraryAccess, /\['insertFromPaste', 'insertFromDrop'\]\.includes\(event\.inputType\)/);
  assert.match(libraryAccess, /doiInput\.addEventListener\('blur'/);
  assert.match(libraryAccess, /resolveIncremental\(\{ force: true \}\)/);
  assert.match(libraryAccess, /navigator\.clipboard\.writeText\(item\.accessUrl\)/);
  assert.match(libraryAccess, /chrome\.tabs\.create\(\{ url: item\.accessUrl, active: true \}\)/);
  assert.doesNotMatch(libraryAccess, /createElement\('time'\)/);
  assert.match(sidepanelCss, /\.library-access-search-results:empty \{ display: none; \}/);
  assert.match(sidepanelCss, /#libraryAccessPanel \{[^}]*flex: 1;[^}]*overflow: hidden;/);
  assert.match(sidepanelCss, /\.library-access-sub-panel \{[^}]*overflow-y: auto;/);
  assert.match(sidepanelHtml, /class="flat-card library-access-search-card"/);
  assert.match(sidepanelCss, /#libraryAccessConfigSubPanel \.library-access-configured-card \{[^}]*max-height: 45%[^}]*flex: 0 1 auto/);
  assert.match(sidepanelCss, /\.library-access-search-card \{[^}]*flex: 1 1 0[^}]*overflow: hidden/);
  assert.match(sidepanelCss, /\.library-access-search-results \{[^}]*max-height: none[^}]*flex: 1 1 auto[^}]*overflow: auto/);
});
